FROM {{base_image}}

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY . .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

CMD ["gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]
